### ISSUE TITLE
add luaprompt to LuaRocks

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#2] opened 2014-10-27 13:03 UTC
see http://luarocks.org/en/Creating_a_rock

**Comment by dpapavas** [comment] 2015-06-08 16:48
Thanks for submitting the patch!  After an initial hesitation on my part to scrap the C-based luap interpreter in favor of a Lua-based version as in your patch, I've decided to do it.  Handling the nightmare that is building and distributing Lua-related binaries is simply not worth it.  I cherry-picked some of your commits and rewrote others in order to keep the coding-style consistent and to fix certain bugs (such as handling of luajit control commands via -j and passing arguments to scripts via the command line).  In any case, I made sure to keep your name in the copyright messages, so as to credit you for your work.

If you use luaprompt regularly, could you please check out the wip branch and give the module and/or standalone-interpreter a go before I make the next release?  Let me know if the rock builds correctly and if all the command-line switches do what they're supposed to be doing, especially in luaJIT, which I've never used.

**Comment by starius** [comment] 2015-06-08 19:06
I can compile and install the code from wip branch (commit 2ea80946c270b6e65 ).

```
luarocks make --local HISTORY_LIBDIR=/usr/lib/x86_64-linux-gnu/ READLINE_LIBDIR=/usr/lib/x86_64-linux-gnu/
```

1. Option `SAVE_RESULTS` is nice.

2. LuaJIT-only options `-j` and `-O` work.

3. Executing a Lua script by luaprompt DOES NOT WORK!

The following commands print nothing.
```
echo 'print "test"' > test.lua
luap test.lua
```

**Comment by dpapavas** [comment] 2015-06-09 13:37
Thanks for spotting that. It was caused by a last-minute rename of a variable.  I made some other changes to make luap as compatible with lua as possible (such as reading a script from stdin).  If you want, you can give it one more check by updating the master branch.  The wip branch was merged amd deleted.  If I (or you) don't spot anything else, I'm going to release it tommorow and upload the rock.

**Comment by starius** [comment] 2015-06-09 16:29
`master` branch was not updated: https://github.com/dpapavas/luaprompt/commits/master

**Comment by dpapavas** [comment] 2015-06-10 09:50
Oops, forgot to push.  Sorry for that.  Try now.

**Comment by starius** [comment] 2015-06-10 10:18
Executing a Lua script by `luap` works.

The problem with command line arguments passed from `luap` to a script detected:

```
$ cat arg.lua
for i = -3, #arg do
    print(i, arg[i])
end

$ lua arg.lua
-3      nil
-2      nil
-1      lua
0       arg.lua
$ luap arg.lua
-3      nil
-2      luajit
-1      -lluarocks.loader
0       /home/user/.luarocks/lib/luarocks/rocks/prompt/dev-1/bin/luap
1       arg.lua

$ lua -i arg.lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
-3      nil
-2      lua
-1      -i
0       arg.lua
> 
$ luap -i arg.lua
Lua 5.1 Copyright (C) 1994-2012 Lua.org, PUC-Rio
luap 0.6 Copyright (C) 2012-2015 Dimitris Papavasiliou, Boris Nagaev
-3      nil
-2      luajit
-1      -lluarocks.loader
0       /home/user/.luarocks/lib/luarocks/rocks/prompt/dev-1/bin/luap
1       -i
2       arg.lua
>  

$ lua arg.lua a
-3      nil
-2      nil
-1      lua
0       arg.lua
1       a
$ luap arg.lua a
-3      nil
-2      luajit
-1      -lluarocks.loader
0       /home/user/.luarocks/lib/luarocks/rocks/prompt/dev-1/bin/luap
1       arg.lua
2       a

$ lua -i arg.lua a
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
-3      nil
-2      lua
-1      -i
0       arg.lua
1       a
> 
$ luap -i arg.lua a
Lua 5.1 Copyright (C) 1994-2012 Lua.org, PUC-Rio
luap 0.6 Copyright (C) 2012-2015 Dimitris Papavasiliou, Boris Nagaev
-3      nil
-2      luajit
-1      -lluarocks.loader
0       /home/user/.luarocks/lib/luarocks/rocks/prompt/dev-1/bin/luap
1       -i
2       arg.lua
3       a
>  
```

`luap` should move arguments in `arg` to the same indices as `lua` does, at least for index >= 0.
See [my pull request](https://github.com/starius/luaprompt/blob/master/luap.lua#L114).

**Comment by dpapavas** [comment] 2015-06-10 16:40
Ah, another obscure feature I was ignorant of.  Thanks for pointing it out!  I don't think I can match `lua`'s behavior concerning negative indices in `arg`, without manually implementing argument parsing, matching the behavior to that of `lua`.  Needless to say I won't consider that, at least until someone complains about the discrepancy.  Until then the last commit in master, should support indices >= 0.

**Comment by starius** [comment] 2015-06-10 18:11
Arguments seem to be parsed properly. Thank you!

> ```
> lua arg.lua -i
> ```
> does not enter interactive mode, but instead passes -i to script. I could find no way to do that using argparse. Anyway, as I've said, we can handle these problems when someone complains about them.

This particular command can be replaced with `luap -- arg.lua -i`. If it is needed, it can be supported by inserting `--` before script argument.

I think, the code is mature for release.

**Comment by dpapavas** [comment] 2015-06-11 09:31
Ok, I made just two more changes:

1. The `-l` switch didn't set a global variable for versions > 5.1, like `lua` does.  I fixed that and also made sure it's handled before any code is run (it was handled after the `-e` switch).

2. I added the `interactive` field to the module table, that's true when stdin and stdout are interactive terminals.  This allows `luap` to work correctly when saying `cat foo.lua | lua` without havind to add a `-`.

This should be the final version so I'll see about uploading the rock and announcing on the list.  Let me know if you find any problems.

**Comment by starius** [comment] 2015-06-11 09:43
> The -l switch didn't set a global variable for versions > 5.1, like lua does. I fixed that and also made sure it's handled before any code is run (it was handled after the -e switch).

Not critical, but `lua` handles `-l` and `-e` in order:

```
$ lua -llpeg -e'print(lpeg.P("1"))'                                                                                
userdata: 0x1c4cc38

$ lua -e'print(lpeg.P("1"))' -llpeg                                                                                
lua: (command line):1: attempt to index global 'lpeg' (a nil value)
stack traceback:
        (command line):1: in main chunk
        [C]: ?
```

I don' know how to make `argparse` handling options in order. This difference is not crucial, anyway.

**Comment by dpapavas** [comment] 2015-06-11 15:49
> Not critical, but `lua` handles `-l` and `-e` in order:
> ...
> I don' know how to make `argparse` handling options in order. This difference is not crucial, anyway

Yes, it's issues like these that I was reffering to when I said that it's not possible to have absolute compatibility with `lua` without reimplementing it's parsing algorithm. `argparse` won't cut but then again, I agree that it probablt doesn't matter.

I've just uploaded the rock, you can find it [here](https://luarocks.org/modules/dpapavas/luaprompt).  Let me know if you run into any trouble with it.

**Comment by starius** [comment] 2015-06-11 18:24
I can install it using the following command:
```
luarocks install luaprompt --local HISTORY_LIBDIR=/usr/lib/x86_64-linux-gnu/ READLINE_LIBDIR=/usr/lib/x86_64-linux-gnu/
```
It works!

**Comment by dpapavas** [comment] 2015-06-12 15:04
I think you can skip the readline-related portion from the command-line.  Judging by the paths you're running Debian or some derivative and for me, it works fine without having to manually specify the readline library locations.

Apart from that I made the release and announced it on the Lua list so this issue is now officially closed!

**Closed by dpapavas** 2015-06-12 15:04 UTC
